service: toy-ts
variablesResolutionMode: 20210326
custom:
  CONFIG: ${file(./config.${opt:stage, self:provider.stage, 'dev'}.js):CONFIG}
provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  lambdaHashingVersion: 20200924
  environment:
    AWS_S3_REGION: ${self:custom.CONFIG.aws.region}
    AWS_S3_ACCESS_KEY_ID: ${self:custom.CONFIG.aws.accessKeyId}
    AWS_S3_SECRET_ACCESS_KEY: ${self:custom.CONFIG.aws.secretAccessKey}
    AWS_S3_BUCKET: ${self:custom.CONFIG.aws.s3.bucket}
    AWS_S3_UPLOADROOT: ${self:custom.CONFIG.aws.s3.uploadRoot}
    AWS_S3_URL: ${self:custom.CONFIG.aws.s3.url}
    AWS_S3_PRIVATE_BUCKET: ${self:custom.CONFIG.aws.s3_private.bucket}
    AWS_S3_PRIVATE_URL: ${self:custom.CONFIG.aws.s3_private.url}

functions:
  demo:
    handler: src/handler.demo
    layers:
      - arn:aws:lambda:ap-northeast-2:147941222526:layer:ts-aws-layer:3

plugins:
  #- serverless-esbuild
  - serverless-plugin-typescript 
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - src/layer/**
    - src/**/*.map
    - package.json
